# Reasonable SHELL configuration for this application
CONFIG_SHELL=n

# Logging
CONFIG_LOG=n

# Hubble Network
CONFIG_HUBBLE_BLE_NETWORK=y

# Bluetooth dependencies
CONFIG_BT=y
CONFIG_BT_BROADCASTER=y

CONFIG_MAIN_STACK_SIZE=2048
